Qualcomm:
  - Qualcomm Incorporated
  - Qualcomm Inc.
Ericsson:
  - Ericsson LM
  - Telefonaktiebolaget LM Ericsson
Nokia:
  - Nokia Bell Labs
Samsung:
  - Samsung Electronics
ZTE:
  - ZTE Corporation
vivo:
  - Vivo Mobile Communications
